# Generated by Django 3.2.9 on 2021-11-07 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sengakuji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('cnt', models.IntegerField()),
            ],
        ),
    ]
